language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
script: $GSERVICES_JSON > google-services.json > ./gradlew assembleDebug check
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
after_success:
  - mv build/outputs/apk/Lawnchair-aosp-debug.apk Travis-$TRAVIS_COMMIT.apk
  - curl -F chat_id="-1001083653933" -F document=@"Travis-$TRAVIS_COMMIT.apk" https://api.telegram.org/bot$BOT_TOKEN/sendDocument