language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install: openssl enc -d -aes-256-cbc -in google-services.json.enc -out google-services.json -k $ENC_PASS
script: ./gradlew assembleDebug check
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
after_success:
  - mv build/outputs/apk/Lawnchair-aosp-debug.apk Lawnchair-$TRAVIS_BUILD_NUMBER.apk
  - curl -F chat_id="-1001083653933" -F document=@"Lawnchair-$TRAVIS_BUILD_NUMBER.apk" https://api.telegram.org/bot$BOT_TOKEN/sendDocument
  - mv build/outputs/mapping/aosp/debug/mapping.txt proguard-$TRAVIS_BUILD_NUMBER.txt
  - curl -F chat_id="152559768" -F document=@"proguard-$TRAVIS_BUILD_NUMBER.txt" https://api.telegram.org/bot$BOT_TOKEN/sendDocument
  - curl -F "status=2" -F "notify=1" -F "notes_type=0" -F "ipa=@app/build/outputs/apk/Lawnchair-aosp-debug.apk" -H "X-HockeyAppToken: $HOCKEYAPP_TOKEN" https://rink.hockeyapp.net/api/2/apps/upload
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "Lawnchair-$TRAVIS_BUILD_NUMBER.apk"
  skip_cleanup: true
  on:
    tags: true
